### ISSUE TITLE
运行出现错误是啥原因？

### ISSUE THREAD

**Issue by lukemin** [CruiseYuGH/emby-alist_forxiaoya#1]
ash-4.4# python3 xiaoya_post.py
{'code': 200, 'message': 'success', 'data': {'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1ZXN0IiwiZXhwIjoxNzIwMTY5MDM2LCJuYmYiOjE3MDI4ODkwMzYsImlhdCI6MTcwMjg4OTAzNn0.ttctWGH2vPF8N1jhKCShEO0ZpyY-h9nq0S5MH5Gz1v4'}}
None 1 for /电视剧/中国/同步更新中/M 美国恐怖故事 1~12/S05
无法显示目录下文件，请刷新重试: **********0
None 1 for /电视剧/中国/同步更新中/M 鸣龙少年 (2023)
无法显示目录下文件，请刷新重试: **********0
None 3 for /电视剧/中国/同步更新中/N 宁安如梦 (2023) 完结/100万个约定之宁安如梦 (2023)
None 3 for /电视剧/中国/同步更新中/N 宁安如梦 (2023) 完结/1080P
None 3 for /电视剧/中国/同步更新中/N 宁安如梦 (2023) 完结/4K
None 3 for /电视剧/中国/同步更新中/N 宁安如梦 (2023) 完结/4K HDR
None 3 for /电视剧/中国/同步更新中/N 宁安如梦 (2023) 完结/4K 杜比
None 3 for /电视剧/中国/同步更新中/N 宁安如梦 (2023) 完结/付费番外+花絮
None 1 for /电视剧/中国/同步更新中/O 偶然遇见的你 어쩌다 마주친 그대 (2023)
无法显示目录下文件，请刷新重试: **********0

**Comment by CruiseYuGH** [comment]
“None 3”的话是这个目录下面没有电视剧。
“ 无法显示目录下文件，请刷新重试: **********0” 这个是正常的请求然后小雅的问题，代码会请求60次不影响。就好比你自己打开小雅的时候也会出现。
#########################
“None 1” 这个我目前没咋遇到，等有空我查一下

**Comment by lukemin** [comment]
if alist_token:
    for xiaoya_dir in ["同步更新", "每日更新/电影/中国/", "每日更新/电影/欧美/", "每日更新/电影/日本/", "每日更新/电影/韩国/"]:
        if xiaoya_dir== "同步更新":
            save_mulu = '/volume3/3TII/xiaoya/media/xiaoya/同步更新/'
            url_path = "/电视剧/中国/同步更新中/"
        elif xiaoya_dir== "每日更新/电影/中国/":
            save_mulu = '/volume3/3TII/xiaoya/media/xiaoya/每日更新/电影/中国/'
            url_path = "/每日更新/电影/中国/"
        elif xiaoya_dir== "每日更新/电影/欧美/":
            save_mulu = '/volume3/3TII/xiaoya/media/xiaoya/每日更新/电影/欧美/'
            url_path = "/每日更新/电影/欧美/"
        elif xiaoya_dir== "每日更新/电影/日本/":
            save_mulu = '/volume3/3TII/xiaoya/media/xiaoya/每日更新/电影/日本/'
            url_path = "/每日更新/电影/日本/"
        elif xiaoya_dir== "每日更新/电影/韩国/":
            save_mulu = '/volume3/3TII/xiaoya/media/xiaoya/每日更新/电影/韩国/'
            url_path = "/每日更新/电影/韩国/"
我emby的目录是/volume3/3TII/xiaoya/media，我这样设置是正确的吗？
如果是正确的，脚本跑完之后，目录里面没有出现响应的文件。

**Comment by CruiseYuGH** [comment]
可以的。但是我目前发现“/每日更新/电影/” 偶尔更新就好，变动不多。  

脚本跑完之后，目录里面没有出现响应的文件。----由于前面有大量的请求，导致当请求“/每日更新/电影/欧美/” （目前代码设定只会请求一次）失败直接退出来了。

我现在干脆定时只跑第一个电视剧的。其他的偶尔改个代码跑下。

**Comment by lukemin** [comment]
建议加上一个sleep命令，在阿里运行的范围内运行。

**Comment by CruiseYuGH** [comment]
这个请求是alist 的服务的返回问题，目前没查到有啥文档。暂时加入一个sleep 30s的逻辑吧。
“ 无法显示目录下文件，请刷新重试: **********0”   --- 这个错误和我本地错误错误码不一样，代码已经修改适配了。

**Comment by lukemin** [comment]
None 3 for /每日更新/电影/中国/不虚此行
None 3 for /每日更新/电影/中国/我经过风暴
Failed to retrieve files. Error: /每日更新/电影/中国/学爸
None 3 for /每日更新/电影/中国/绝地追击
None 3 for /每日更新/电影/中国/树上有个好地方/树上有个好地方2：美术老师的放羊班
Failed to retrieve files. Error: /每日更新/电影/中国/熊出没·伴我“熊芯”
Failed to retrieve files. Error: /每日更新/电影/中国/熊出没·伴我“熊芯”
None 3 for /每日更新/电影/中国/茶啊二中
None 3 for /每日更新/电影/中国/极寒之城
Failed to retrieve files. Error: /每日更新/电影/中国/长空之王
Failed to retrieve files. Error: /每日更新/电影/中国/长空之王
None 3 for /每日更新/电影/中国/长空之王
现在又出现新的错误了。

**Comment by CruiseYuGH** [comment]
Failed to retrieve files. Error: /每日更新/电影/中国/长空之王 这个是正常的，他是碰到“ 无法显示目录下文件，请刷新重试: **********0” 的时候再次请求。你可以看生成的结果如果这个在小雅的网站上存在相关的视频，这个也会有的。

**Comment by CruiseYuGH** [comment]
你上面这个日志的话，
 “/每日更新/电影/中国/学爸” 应该是存在视频的。
但是  “/每日更新/电影/中国/长空之王” 应该不会有这个文件，因为在小雅的网站下同样是空的。

**Comment by lukemin** [comment]
的确是这样的，谢谢回复。
